spring:
  application:
    name: internet-banking-mail-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true

server:
  port: ${MAIL_SERVER_PORT}
