spring:
  application:
    name: internet-banking-api
  datasource:
    url: jdbc:postgresql://localhost:5432/internet_banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  # Async processing configuration
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: "async-task-"

server:
  port: 8081
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never

jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm1234567890
  expiration: 86400000 # 24 hours in milliseconds
  issuer: internet-banking-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# Logging configuration for debugging Feign calls
logging:
  level:
    edu.ifba.internet_banking_main_api.clients: DEBUG
    edu.ifba.internet_banking_main_api.services.EmailNotificationService: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    try-it-out-enabled: true
  packages-to-scan: edu.ifba.internet_banking_main_api.controllers
  show-actuator: false
