spring:
  application:
    name: internet-banking-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: internet-banking-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    try-it-out-enabled: true
  packages-to-scan: edu.ifba.internet_banking_main_api.controllers
  show-actuator: false
