spring:
  application:
    name: Internet Banking API
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: internet-banking-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true
