spring:
  application:
    name: Internet Banking API
  datasource:
    url: jdbc:postgresql://localhost:5432/internet_banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never
jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm1234567890
  expiration: 86400000 # 24 hours in milliseconds
  issuer: internet-banking-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
